# Generated by Django 5.2 on 2025-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_rename_instrument_control_instrumentcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='not_defined')),
                ('px_open', models.FloatField(default=0.0)),
                ('px_high', models.FloatField(default=0.0)),
                ('px_low', models.FloatField(default=0.0)),
                ('px_close_1d', models.FloatField(default=0.0)),
                ('px_volume', models.IntegerField(default=0)),
                ('open_int', models.IntegerField(default=0)),
                ('instrument', models.CharField(default='not_defined', max_length=50)),
                ('sectype', models.CharField(default='not_defined', max_length=20)),
                ('exchange', models.CharField(default='not_defined', max_length=10)),
                ('crncy', models.CharField(default='not_defined', max_length=10)),
                ('tick_size', models.FloatField(default=0.0)),
                ('tick_value', models.FloatField(default=0.0)),
                ('point_value', models.FloatField(default=0.0)),
                ('contract_value', models.FloatField(default=0.0)),
                ('near', models.FloatField(default=0.0)),
                ('far', models.FloatField(default=0.0)),
                ('st_dev', models.FloatField(default=0.0)),
                ('no_days', models.IntegerField(default=0)),
            ],
        ),
    ]
