# Generated by Django 5.2 on 2025-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_instrumentdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentdata',
            name='date',
            field=models.DateField(default='01-01-2000'),
        ),
    ]
