# Generated by Django 5.2 on 2025-04-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_instrumentdata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstrumentData',
        ),
    ]
