# Generated by Django 5.2 on 2025-04-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_delete_instrumentdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='currency',
            new_name='Currency',
        ),
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='exchange_rate',
            new_name='Exchange_rate',
        ),
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='instrument_weights',
            new_name='Instrument_Weights',
        ),
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='instrument_name',
            new_name='Instruments',
        ),
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='point_value',
            new_name='Point_Value',
        ),
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='standard_cost',
            new_name='Standard_Cost',
        ),
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='tic_size',
            new_name='Tic_Size',
        ),
        migrations.RenameField(
            model_name='instrumentcontrol',
            old_name='tic_value',
            new_name='Tic_Value',
        ),
    ]
