# Generated by Django 5.2 on 2025-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=50)),
                ('point_value', models.FloatField()),
                ('tic_size', models.FloatField()),
                ('tic_value', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('exchange_rate', models.FloatField()),
                ('instrument_weights', models.FloatField()),
                ('bid', models.FloatField()),
                ('offer', models.FloatField()),
                ('execution_cost', models.FloatField()),
                ('clearing_cost', models.FloatField()),
                ('standard_cost', models.FloatField()),
            ],
        ),
    ]
