# Generated by Django 5.2 on 2025-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('px_open', models.FloatField(blank=True, null=True)),
                ('px_high', models.FloatField(blank=True, null=True)),
                ('px_low', models.FloatField(blank=True, null=True)),
                ('px_close_1d', models.FloatField(blank=True, null=True)),
                ('px_volume', models.BigIntegerField(blank=True, null=True)),
                ('open_int', models.BigIntegerField(blank=True, null=True)),
                ('sectype', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('crncy', models.CharField(blank=True, max_length=10, null=True)),
                ('tick_size', models.FloatField(blank=True, null=True)),
                ('tick_value', models.FloatField(blank=True, null=True)),
                ('point_value', models.FloatField(blank=True, null=True)),
                ('contract_value', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('st_dev', models.FloatField(blank=True, null=True)),
                ('no_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
