# Generated by Django 5.2 on 2025-04-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_instrumentdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='Instrument_Control',
        ),
        migrations.DeleteModel(
            name='InstrumentDetails',
        ),
    ]
