# Generated by Django 5.2 on 2025-04-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_rename_instrument_instrument_control_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument_Control',
            new_name='InstrumentControl',
        ),
    ]
