# Generated by Django 5.2 on 2025-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_instrumentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentdata',
            name='date',
            field=models.DateField(),
        ),
    ]
